version: '3.8'

services:
  web:
    build: .
    command: uvicorn main:app --reload --host 0.0.0.0
    volumes:
      - .:/app
    ports:
      - 8000:8000
    environment:
      - DATABASE_URL=postgresql://transfer:transfer@db:5432/transferdb
    depends_on:
      - db
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      - POSTGRES_USER=transfer
      - POSTGRES_PASSWORD=transfer
      - POSTGRES_DB=transferdb
volumes:
  postgres_data:
